import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({articles}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {/* <p>{
          articles.data.map((article, i) => (<div>{article.name}</div> ))
        }</p> */}
      </main>

      <footer className={styles.footer}>
        <center>All Rights Reserved.</center>
      </footer>
    </div>
  )
}


// export async function getServerSideProps(context) {
//   let res = await fetch("http://localhost:3000/api/posts", {
//     method: "GET",
//     headers: {
//       "Content-Type": "application/json",
//     },
//   });
//   let articles = await res.json();

//   return {
//     props: { articles }
//   };
// }